<?php 
$row = $this->getRow();
$attributes = $this->getAttributes();
$mode = ($row->entity_id) ? 'Edit' : 'Add';
?>
<form action="<?php echo $this->getUrl('save'); ?>" method="POST">
<div align="center" class="w-100 container">
	<div class="w-50 align-items-center row">
		<div align="left" class="col-8">
			<h2><?php echo $mode." item"; ?></h2>
		</div>
		<div align="right" class="col-2">
			
			<a href="<?php echo $this->getUrl('grid',null,[],true); ?>" class="btn btn-danger">Cancel</a>
		</div>
		<div align="right" class="col-2">
			<button class="btn btn-primary" name="submit">Save</button>
		</div>
	</div>
	<div class="w-50 mt-2">
		<table class="table table-striped table-hover mt-2">
			<tr>
				<th colspan="2">
					item information
				</th>
			</tr>
			<tr>
				<td>Sku</td>
				<td><input type="text" name="item[sku]" class="form-control" value="<?php echo $row->sku; ?>"></td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="item[status]" class="form-select">
						<?php foreach ($row->getStatusOptions() as $key => $value): 
							$selected = ($key == $row->getStatus()) ? 'selected' : '';
						?>
						<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<?php if($attributes): ?>
			<?php foreach ($attributes->getData() as $attribute) : ?>
				<tr>
					<td><?php echo $attribute->name; ?></td>
					<td>
						<?php $inputType = $this->getLayout()->createBlock('Eav_Attribute_InputType')->setAttribute($attribute)->setRow($row)->render(); ?>
					</td>
				</tr>
			<?php endforeach; ?>
			<?php endif; ?>
		</table>
	</div>
</div>
</form>
