<div class="d-flex justify-content-around">
	<div>
		<a href="?a=index&c=product" class="text-white text-decoration-none">Product</a>
	</div>
	<div>
		<a href="?a=index&c=category" class="text-white text-decoration-none">Category</a>
	</div>
	<div>
		<a href="?a=grid&c=customer" class="text-white text-decoration-none">Customer</a>
	</div>
	<div>
		<a href="?a=grid&c=salesman" class="text-white text-decoration-none">Salesman</a>
	</div>
	<div>
		<a href="?a=grid&c=vendor" class="text-white text-decoration-none">Vendor</a>
	</div>
	<div>
		<a href="?a=index&c=shipping" class="text-white text-decoration-none">Shipping method</a>
	</div>
	<div>
		<a href="?a=index&c=payment" class="text-white text-decoration-none">Payment method</a>
	</div>
	<div>
		<a href="?a=index&c=admin" class="text-white text-decoration-none">Admin</a>
	</div>
	<div>
		<a href="?a=grid&c=eav_attribute" class="text-white text-decoration-none">Eav attribute</a>
	</div>
	<div>
		<a href="?a=grid&c=item" class="text-white text-decoration-none">Item</a>
	</div>
	<div>
		<a href="?a=grid&c=brand" class="text-white text-decoration-none">Brand</a>
	</div>
</div>
