<div class="d-flex justify-content-around">
	<div>
		<a href="?c=product&a=index" class="text-white text-decoration-none">Product</a>
	</div>
	<div>
		<a href="?c=category&a=index" class="text-white text-decoration-none">Category</a>
	</div>
	<div>
		<a href="?c=customer&a=index" class="text-white text-decoration-none">Customer</a>
	</div>
	<div>
		<a href="?c=salesman&a=index" class="text-white text-decoration-none">Salesman</a>
	</div>
	<div>
		<a href="?c=vendor&a=index" class="text-white text-decoration-none">Vendor</a>
	</div>
	<div>
		<a href="?c=shipping&a=index" class="text-white text-decoration-none">Shipping method</a>
	</div>
	<div>
		<a href="?c=payment&a=index" class="text-white text-decoration-none">Payment method</a>
	</div>
	<div>
		<a href="?c=admin&a=index" class="text-white text-decoration-none">Admin</a>
	</div>
	<div>
		<a href="?c=eav_attribute&a=index" class="text-white text-decoration-none">Eav attribute</a>
	</div>
	<div>
		<a href="?c=item&a=index" class="text-white text-decoration-none">Item</a>
	</div>
	<div>
		<a href="?c=brand&a=index" class="text-white text-decoration-none">Brand</a>
	</div>
	<div>
		<a href="?c=quote&a=quote" class="text-white text-decoration-none">Quote</a>
	</div>
</div>
