<?php 
$product = $this->getProduct();
$attributes = $this->getAttributes();
$mode = ($product->product_id) ? 'Edit' : 'Add';
?>
<form action="<?php echo $this->getUrl('save'); ?>" method="POST">
<div align="center" class="w-100 container">
	<div class="w-50 align-items-center row">
		<div align="left" class="col-8">
			<h2><?php echo $mode." product"; ?></h2>
		</div>
		<div align="right" class="col-2">
			<a href="<?php echo $this->getUrl('grid',null,[],true); ?>" class="btn btn-danger">Cancel</a>
		</div>
		<div align="right" class="col-2">
			<button class="btn btn-primary" name="submit">Save</button>
		</div>
	</div>
	<div class="w-50 mt-2">
		<table class="table table-striped table-hover mt-2">
			<tr>
				<th colspan="2">
					Product information
				</th>
			</tr>
			<tr>
				<td>
					Name
				</td>
				<td>
					<input type="text" name="product[name]" class="form-control" value="<?php echo $product->name; ?>">
				</td>
			</tr>
			<tr>
				<td>
					Sku
				</td>
				<td>
					<input type="text" name="product[sku]" class="form-control" value="<?php echo $product->sku; ?>">
				</td>
			</tr>
			<tr>
				<td>
					Cost
				</td>
				<td>
					<input type="number" name="product[cost]" class="form-control" value="<?php echo $product->cost; ?>">
				</td>
			</tr>
			<tr>
				<td>
					Price
				</td>
				<td>
					<input type="number" name="product[price]" class="form-control" value="<?php echo $product->price; ?>">
				</td>
			</tr>
			<tr>
				<td>
					Quantity
				</td>
				<td>
					<input type="number" name="product[quantity]" class="form-control" value="<?php echo $product->quantity; ?>">
				</td>
			</tr>
			<tr>
				<td>
					Description
				</td>
				<td>
					<textarea class="form-control" name="product[description]" style="height: 50px;resize: none;"><?php echo $product->description; ?></textarea>
				</td>
			</tr>
			<tr>
				<td>
					Status
				</td>
				<td>
					<select name="product[status]" class="form-select">
						<?php foreach ($product->getStatusOptions() as $key => $value): 
							$selected = ($key == $product->getStatus()) ? 'selected' : '';
						?>
						<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td>
					Color
				</td>
				<td>
					<?php $color = ['1'=>'Brown','2'=>'Black','3'=>'White','4'=>'Red','5'=>'Silver','6'=>'Blue','7'=>'Green']; ?>
					<select name="product[color]" class="form-select">
						<?php foreach ($color as $key => $value): ?>
						<option value="<?php echo $key; ?>"
						<?php 
						if($key == $product->color){
							echo 'selected';
						}
						?>>
						<?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td>
					Material
				</td>
				<td>
					<?php $material = ['1'=>'Plastic','2'=>'Glass','3'=>'Metals','4'=>'Wood','5'=>'Paper','6'=>'Fibers','7'=>'Ceramic'] ?>
					<select name="product[material]" class="form-select">
						<?php foreach ($material as $key => $value): ?>
						<option value="<?php echo $key; ?>"
						<?php 
						if($key == $product->material){
							echo 'selected';
						}
						?>>
						<?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<?php if ($attributes) : ?>
			<?php foreach($attributes->getData() as $key => $attribute): ?>
			<tr>
				<td>
					<?php echo $attribute->name; ?>
				</td>
				<td>
					<?php $this->getLayout()->createBlock('Eav_Attribute_InputType')->setAttribute($attribute)->setRow($product)->render(); ?>
				</td>
			</tr>
			<?php endforeach; ?>
			<?php endif; ?>
		</table>
	</div>
</div>
</form>
