<?php 
$products = $this->getProducts();
?>
<div align="center" class="container w-100">
	<div class="d-flex align-items-center row">
		<div class="col-6" align="left">
			<h2>Manage Products</h2>
		</div>
		<div class="col-6" align="right">
			<a href="<?php echo $this->getUrl('add'); ?>">
				<button class="btn btn-primary">Add product</button>
			</a>
		</div>
	</div>	
	<div class="w-100 mt-2">
		<table class="table table-striped table-hover">
			<?php if ($products) { ?>
			<tr class="table-dark">
				<th>Product ID</th>
				<th>Name</th>
				<th>Sku</th>
				<th>Cost</th>
				<th>Price</th>
				<th>Quantity</th>
				<th>Description</th>
				<th>Status</th>
				<th>Color</th>
				<th>Material</th>
				<th>Small</th>
				<th>Thumb</th>
				<th>Base</th>
				<th>Created at</th>
				<th>Updated at</th>
				<th>Media</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<?php 
			foreach ($products->getData() as $product):
			?>
			<tr>
				<td><?php echo $product->product_id; ?></td>
				<td><?php echo $product->name; ?></td>
				<td><?php echo $product->sku; ?></td>
				<td><?php echo $product->cost; ?></td>
				<td><?php echo $product->price; ?></td>
				<td><?php echo $product->quantity; ?></td>
				<td><?php echo $product->description; ?></td>
				<td><?php echo $product->getStatusText(); ?></td>
				<td><?php $colors = ['1'=>'Brown','2'=>'Black','3'=>'White','4'=>'Red','5'=>'Silver','6'=>'Blue','7'=>'Green']; 
					foreach ($colors as $key => $color) {
						if ($product->color == $key) {
							echo $color;
						}
					} ?>
				</td>
				<td><?php $materials = ['1'=>'Plastic','2'=>'Glass','3'=>'Metals','4'=>'Wood','5'=>'Paper','6'=>'Fibers','7'=>'Ceramic']; 
					foreach ($materials as $key => $material) {
					 	if ($product->material == $key) {
					 		echo $material;
					 	}
					 } ?>
				</td>
				<td><?php echo $product->small_id; ?></td>
				<td><?php echo $product->thumb_id; ?></td>
				<td><?php echo $product->base_id; ?></td>
				<td>
					<?php 
					if ($product->created_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($product->created_at)); 
					 }
					?>
				</td>
				<td>
					<?php 
					if ($product->updated_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($product->updated_at)); 
					 }
					?>
				</td>
				<td><a href="<?php echo $this->getUrl(null,'product_media',['id'=>$product->product_id]); ?>"><img height="30px" src="Resources/images/media.png"></a></td>
				<td><a href="<?php echo $this->getUrl('edit',null,['id'=>$product->product_id]); ?>"><img height="25px" src="Resources/images/edit.png"></a></td>
				<td><a href="<?php echo $this->getUrl('delete',null,['id'=>$product->product_id]); ?>"><img height="25px" src="Resources/images/delete.png"></a></td>
			</tr>
			<?php 
			endforeach; }
			else{
			?>
			<tr>
				<td colspan="15">
					<h3>There is no record</h3>
				</td>
			</tr>
			<?php } ?>
		</table>
	</div>
</div>
