<?php 
$shipping = $this->getShipping();
$attributes = $this->getAttributes();
$mode = ($shipping->shipping_method_id) ? 'Edit' : 'Add';
?>
<div align="center" class="w-100 container">
	<form method="POST" action="<?php echo $this->getUrl('save'); ?>" id="shipping-form">
	<div class="w-50 align-items-center d-flex row">
		<div align="left" class="col-8">
			<h2><?php echo $mode." Shipping method"; ?></h2>
		</div>
		<div align="right" class="col-2">
			<a onclick="ajax.setUrl('<?php echo $this->getUrl('grid',null,[],true); ?>').call()" class="btn btn-danger">Cancel</a>
		</div>
		<div align="right" class="col-2">
			<input type="button" class="btn btn-primary" onclick="ajax.setForm('shipping-form').call()" value="Save">
		</div>
	</div>
	<div class="w-50 mt-2">
		<table class="table table-striped table-hover">
			<tr>
				<th colspan="2">Shipping Method information</th>
			</tr>
			<tr>
				<td>Name</td>
				<td><input type="text" name="shipping[name]" class="form-control" value="<?php echo $shipping->name; ?>"></td>
			</tr>
			<tr>
				<td>Amount</td>
				<td><input type="number" name="shipping[amount]" class="form-control" value="<?php echo $shipping->amount; ?>"></td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="shipping[status]" class="form-control">
						<?php foreach ($shipping->getStatusOptions() as $key => $value): 
							$selected = ($key == $shipping->getStatus()) ? 'selected' : '';
						?>
						<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			
			<?php if ($attributes) : ?>
			<?php foreach($attributes->getData() as $key => $attribute): ?>
			<tr>
				<td>
					<?php echo $attribute->name; ?>
				</td>
				<td>
					<?php $this->getLayout()->createBlock('Eav_Attribute_InputType')->setAttribute($attribute)->setRow($shipping)->render(); ?>
				</td>
			</tr>
			<?php endforeach; ?>
			<?php endif; ?>
		</table>
	</div>
	</form>
</div>
