<?php 
$shippings = $this->getShippings();
?>
<div align="center" class="container w-100">
	<div class="w-90 align-items-center d-flex row">
		<div align="left" class="col-6">
			<h2>Manage Shipping Methods</h2>
		</div>
		<div align="right" class="col-6">
			<a href="<?php echo $this->getUrl('add'); ?>"><button class="btn btn-primary">Add Shipping method</button></a>
		</div>
	</div>
	<div class="w-90 mt-2">
		<table class="table table-striped table-hover">
			<?php if ($shippings) { ?>
			<tr class="table-dark">
				<th>Shipping Method ID</th>
				<th>Name</th>
				<th>Amount</th>
				<th>Status</th>
				<th>Created At</th>
				<th>Updated At</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<?php foreach($shippings->getData() as $shipping): ?>
			<tr>
				<td><?php echo $shipping->shipping_method_id ?></td>
				<td><?php echo $shipping->name ?></td>
				<td><?php echo $shipping->amount ?></td>
				<td><?php echo $shipping->getStatusText(); ?></td>
				<td>
					<?php 
					if ($shipping->created_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($shipping->created_at)); 
					 }
					?>
				</td>
				<td>
					<?php 
					if ($shipping->updated_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($shipping->updated_at)); 
					 }
					?>
				</td>
				<td><a href="<?php echo $this->getUrl('edit', null, ['id' => $shipping->shipping_method_id]); ?>"><img style="height: 25px;" src="Resources/images/edit.png"></a></td>
				<td><a href="<?php echo $this->getUrl('delete', null, ['id' => $shipping->shipping_method_id]); ?>"><img style="height: 25px;" src="Resources/images/delete.png"></a></td>
			</tr>
			<?php endforeach;  } 
			else{ ?>
			<tr>
				<td colspan="8">
					<h3>There is no record</h3>
				</td>
			</tr>
			<?php } ?>
		</table>
	</div>
</div>
	