<?php 
$row = $this->getRow();
$mode = ($row->brand_id) ? 'Edit' : 'Add';
?>
<div align="center" class="w-100 container">
	<form action="<?php echo $this->getUrl('save'); ?>" method="POST" enctype="multipart/form-data">
	<div class="w-50 align-items-center d-flex row">
		<div align="left" class="col-8">
			<h2><?php echo $mode." brand" ?></h2>
		</div>
		<div align="right" class="col-2">
			<a href="<?php echo $this->getUrl('grid',null,[],true); ?>" class="btn btn-danger">Cancel</a>
		</div>
		<div align="right" class="col-2">
			<button class="btn btn-primary" name="submit">Save</button>
		</div>
	</div>
	<div class="w-50 mt-2">
		<table class="table table-striped table-hover">
			<tr>
				<th colspan="2">Brand information</th>
			</tr>
			<tr>
				<td>Name</td>
				<td><input type="text" name="brand[name]" value="<?php echo $row->name; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>Description</td>
				<td><input type="text" name="brand[description]" value="<?php echo $row->description; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>image</td>
				<td><input type="file" name="brand[image]" class="form-control"></td>
			</tr>
		</table>
	</div>
	</form>
</div>
