<?php 
$admin = $this->getAdmin(); 
$mode = ($admin->admin_id) ? 'Edit' : 'Add';
?>
<form action="<?php echo $this->getUrl('save'); ?>" method="post" id="admin-form"> 
<div align="center" class="w-100 container">
	<div align="left" class="w-50 align-items-center d-flex row">
		<div class="col-8">
			<h2><?php echo $mode." admin"; ?></h2>
		</div>
		<div class="col-4 d-flex align-items-center">
			<div align="right" class="col-6">
				<a onclick="ajax.setUrl('<?php echo $this->getUrl('grid',null,[],true); ?>').call()" class="btn btn-danger">Cancel</a>
			</div>
			<div align="right" class="col-6">
				<button name="submit" type="button" onclick="ajax.setForm('admin-form').call()" class="btn btn-primary">Save</a>
			</div>
		</div>
	</div>
	<div class="w-50 mt-2">
		<table class="table table-striped table-hover">
			<th colspan="2">
				Admin's information
			</th>
			<tr>
				<td>Name</td>
				<td><input type="text" name="admin[name]" value="<?php echo $admin->name; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>Email</td>
				<td><input type="email" name="admin[email]" value="<?php echo $admin->email; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>Password</td>
				<td><input type="password" name="admin[password]" value="<?php echo $admin->password; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="admin[status]" class="form-select">
						<?php foreach($admin->getStatusOptions() as $key => $value): 
						$selected = ($key == $admin->getStatus()) ? 'selected' : '';
						?>
						<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
					<?php endforeach; ?>
					</select>
				</td>
			</tr>
		</table>
	</div>
</div>
</form>
