<?php
$admins = $this->getAdmins();
?>
<div align="center" class="container w-100">
	<div class="w-90 d-flex align-items-center row">
		<div align="left" class="col-6">
			<h2>Manage Admins</h2>
		</div>
		<div align="right" class="col-6">
			<a href="<?php echo $this->getUrl('add'); ?>"><button class="btn btn-primary">Add admin</button></a>
		</div>
	</div>
	<div class="w-90 mt-2">
		<table class="table table-striped table-hover">
			<?php if (!$admins): ?>
				<tr>
					<td colspan="8" align="center"><h3>There is no record.</h3></td>
				</tr>
			<?php else: ?>
			<tr class="table-dark">
				<th>Admin ID</th>
				<th>Name</th>
				<th>Email</th>
				<th>Status</th>
				<th>Created At</th>
				<th>Updated At</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<?php foreach($admins->getData() as $admin): ?>
			<tr>
				<td><?php echo $admin->admin_id; ?></td>
				<td><?php echo $admin->name; ?></td>
				<td><?php echo $admin->email; ?></td>
				<td><?php echo $admin->getStatusText(); ?></td>
				<td><?php echo date('Y/m/d h:i:s a', strtotime($admin->created_at)); ?></td>
				<td><?php echo ($admin->updated_at) ? date('Y/m/d h:i:s a', strtotime($admin->updated_at)) : ''; ?></td>
				<td><a href="<?php echo $this->getUrl('edit',null,['id'=>$admin->admin_id]); ?>"><img style="height: 25px;" src="Resources/images/edit.png"></a></td>
				<td><a href="<?php echo $this->getUrl('delete',null,['id'=>$admin->admin_id]); ?>"><img style="height: 25px;" src="Resources/images/delete.png"></a></td>
			</tr>
		<?php endforeach; endif; ?>
		</table>
	</div>
</div>
