<?php 
$attribute = $this->getAttribute();
$mode = ($attribute->attribute_id) ? 'Edit' : 'Add';
if ($this->getOptions()){
	$options = $this->getOptions()->getData();
}
else{
	$options = [];
}
?>
<form action="<?php echo $this->getUrl('save'); ?>" method="POST">
<div align="center" class="container w-100">
	<div class="w-50 align-items-center d-flex row">
		<div align="left" class="col-8">
			<h2><?php echo $mode." attribute"; ?></h2>
		</div>
		<div align="right" class="col-2">
			<a href="<?php echo $this->getUrl('grid',null,[],true); ?>" class="btn btn-danger">Cancel</a>
		</div>
		<div align="right" class="col-2">
			<button class="btn btn-primary" name="submit">Save</button>
		</div>
	</div>
	<div class="w-50 mt-2">
		<table class="table table-striped table-hover">
			<tr>
				<th colspan="2">
					Attribute information
				</th>
			</tr>
			<tr>
				<td>Code</td>
				<td>
					<input type="text" name="attribute[code]" class="form-control" value="<?php echo $attribute->code; ?>">
				</td>
			</tr>
			<tr>
				<td>Name</td>
				<td>
					<input type="text" name="attribute[name]" class="form-control" value="<?php echo $attribute->name; ?>">
				</td>
			</tr>
			<tr>
				<td>Input type</td>
				<td>
					<select name="attribute[input_type]" class="form-control" id="inputTypeSelect">
					<?php $inputType = ['textbox' => 'Text Box', 'textarea' => 'Text Area', 'checkbox' => 'Check Box', 'radio' => 'Radio', 'select' => 'Select', 'multiselect' => 'Multi Select']; 
						foreach ($inputType as $key => $value):
					?>
						<option value="<?php echo $key; ?>" 
							<?php echo ($key == $attribute->input_type) ? 'selected' : '';?>>
							<?php echo $value; ?>
						</option>
					<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td>Backend type</td>
				<td>
					<select name="attribute[backend_type]" class="form-control">
					<?php $backendType = ['int' => 'Integer', 'decimal' => 'Decimal', 'datetime' => 'Date and Time', 'varchar' => 'Varchar', 'text' => 'Text']; 
						foreach ($backendType as $key => $value):
					?>
						<option value="<?php echo $key; ?>" 
							<?php echo ($key == $attribute->backend_type) ? 'selected' : '';?>>
							<?php echo $value; ?>
						</option>
					<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="attribute[status]" class="form-control">
						<?php foreach ($attribute->getStatusOptions() as $key => $value): 
							$selected = ($key == $attribute->getStatus()) ? 'selected' : '';
						?>
						<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td>Backend Model</td>
				<td>
					<input type="text" name="attribute[backend_model]" class="form-control" value="<?php echo $attribute->backend_model; ?>">
				</td>
			</tr>
		</table>
	</div>
</div>
<div style="border: 1px solid red; width: 300px;display: none;margin: auto;" id="inputTypeOptionDiv">
	<table class="table table-striped table-hover">
		<tbody id="inputTypeOptionTable">
			<thead>
				<tr>
					<td>&nbsp;</td>
					<td><input type="button" name="add" value="ADD" class="btn btn-primary" id="addOption"></td>
				</tr>
			</thead>
			<?php foreach($options as $key => $option): ?>
			<tr>
				<td><input type="text" name="option[exist][<?php echo $option->option_id; ?>]" value="<?php echo $option->name; ?>" class="form-control"></td>
				<td><input type="button" name="remove" value="REMOVE" class="btn btn-danger removeOption"></td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
</form>
<table style="display: none">
	<tbody id="inputTypeOptionDefault">
		<tr>
			<td><input type="text" name="option[new][]" class="form-control"></td>
			<td><input type="button" name="remove" value="REMOVE" class="btn btn-danger removeOption"></td>
		</tr>
	</tbody>
</table>
<script type="text/javascript">

$(".removeOption").click(function () {
	console.log($(this).parent().parent().remove());
});

$("#addOption").click(function () {
	$("#inputTypeOptionTable").prepend($('#inputTypeOptionDefault').html());
});

$("#inputTypeSelect").change(function () {
	var inputType = $(this);
	var values = ['select', 'multiselect', 'checkbox', 'radio'];
	if (jQuery.inArray(inputType.val(), values) == -1) {
		$('#inputTypeOptionDiv').hide();
	}
	else{
		$('#inputTypeOptionDiv').show();
	}
});

$(document).ready(function () {
	$("#inputTypeSelect").trigger('change');
});

</script>
