<div align="center" class="w-100 container">
	<div align="left" class="w-50 container">
		<h2>Add Media</h2>
	</div>
</div>
<form action="<?php echo $this->getUrl('insert'); ?>" method="POST" enctype="multipart/form-data">
<div align="center" class="container w-100 mt-2">
	<div class="w-50 row">
		<div align="left" class="col-6">
			<a href="<?php echo $this->getUrl('grid'); ?>" class="btn btn-danger">cancel</a>
		</div>
		<div align="right" class="col-6">
			<input type="submit" value="Upload image" class="btn btn-primary">
		</div>
	</div>
	<br>
	<div class="w-50 container">
		<table class="table table-striped table-hover">
			<tr>
				<td>Upload image</td>
				<td align="left"><input type="file" name="image" class="form-control"></td>
			</tr>
			<tr>
				<td>Name</td>
				<td align="left"><input type="text" name="name" class="form-control"></td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="status" class="form-control">
						<?php 
						$media = Ccc::getModel('Product_Media');
						foreach ($media->getStatusOptions() as $key => $value): 
						$selected = ($key == $media->getStatus()) ? 'selected' : '';
						?>
						<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
		</table>
	</div>
</div>
</form>
	