<!DOCTYPE html>
<html>
<?php echo $this->getChildHtml('head'); ?>
<body>
	<table width="100%" cellpadding="4">
		<tr height="70px">
			<td colspan="3" class="bg-black sticky-sm-top"><?php echo $this->getChildHtml('header'); ?></td>
		</tr>
		<tr height="50px">
			<td colspan="3" align="center" id="message"><?php echo $this->getChildHtml('message'); ?></td>
		</tr>
		<tr height="200px">
			<td width="100%" align="center" class="mt-3"><?php echo $this->getChildHtml('content'); ?></td>
		</tr>
		<tr height="80px">
			<td colspan="3" class="fixed-bottom bg-secondary-subtle"><?php echo $this->getChildHtml('footer'); ?></td>
		</tr>
	</table>
</body>
</html>