<!DOCTYPE html>
<html>
<?php $this->createBlock('Html_Head')->render(); ?>
<body>
	<table width="100%" cellpadding="4">
		<tr height="70px">
			<td colspan="3" class="bg-black sticky-sm-top"><?php $this->getChild('header')->render(); ?></td>
		</tr>
		<tr height="50px">
			<td colspan="3" align="center"><?php $this->getChild('message')->render(); ?></td>
		</tr>
		<tr height="200px">
			<td width="20%"><?php $this->getChild('left')->render(); ?></td>
			<td width="80%"><?php $this->getChild('content')->render(); ?></td>
		</tr>
		<tr height="80px">
			<td colspan="3" class="fixed-bottom bg-secondary-subtle"><?php $this->getChild('footer')->render(); ?></td>
		</tr>
	</table>
</body>
</html>