<?php $customers = $this->getCustomers(); ?>
<div align="right">
<select class="form-select mb-3" style="width: 30%" name="customer" id="changeCustomer">
	<option value="0">select customer</option>
	<?php foreach($customers->getData() as $key => $customer): ?>
	<option value="<?php echo $customer->customer_id; ?>" 
		<?php echo ($this->getRequest()->getParam('customerId') == $customer->customer_id) ? 'selected' : ''; ?>>
		<?php echo $customer->first_name."-".$customer->customer_id; ?></option>
	<?php endforeach; ?>
</select>
</div>

<script type="text/javascript">

$("#changeCustomer").change(function() {
	if (this.value == 0) {
		ajax.setUrl('http://localhost/newmvc-sahil-solanki/index.php?a=quote&c=quote').call();
	} else {
		var id = this.value;
		ajax.setUrl('http://localhost/newmvc-sahil-solanki/index.php?a=quote&c=quote&customerId='+id).call();
	}
});

</script>