<?php $items = $this->getItems(); ?>
<div id="itemTable">
<form action="<?php echo $this->getUrl('saveItems'); ?>" method="post">
	<div class="row" style="width: 80%;margin: 10px;">
		<div class="col-10" align="right"><a class="btn btn-danger" id="cancelItemTable">Cancel</a></div>
		<div class="col-2" align="right"><button class="btn btn-primary" name="submit">Add selected item</button></div>
	</div>
	<div style="width: 80%" class="mt-3">
		<table class="table table-striped table-hover"  border="2px">
			<?php if(!$items): ?>
			<tr>
				<th colspan="2">There is no record</th>
			</tr>	
			<?php else: ?>
			<tr>
				<th>Image</th>
				<th>Name</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Row Total</th>
				<th>Action</th>
			</tr>
			<?php foreach ($items->getData() as $item) : ?>
			<tr>
				<td></td>
				<td><?php echo $item->name; ?></td>
				<td width="10%"><input type="number" name="item[quantity]" class="form-control"></td>
				<td><?php echo $item->price; ?></td>
				<td><?php echo 'total'; ?></td>
				<td><input type="checkbox" name="add[]"></td>
			</tr>
			<?php endforeach; ?>
			<?php endif; ?>
		</table>
	</div>	
</form>
</div>

<form action="<?php echo $this->getUrl('saveQuoteItems'); ?>" method="post">
	<div class="row mt-3" style="width: 80%;">
		<div class="col-10" align="right"><a href="<?php echo $this->getUrl('quote'); ?>" class="btn btn-danger">Update</a></div>
		<div class="col-2" align="right"><button class="btn btn-primary" name="submit">New item</button></div>
	</div>
	<div style="width: 80%" class="mt-3">
		<table class="table table-striped table-hover"  border="2px">
			<?php if(!$items): ?>
			<tr>
				<th colspan="2">There is no record</th>
			</tr>	
			<?php else: ?>
			<tr>
				<th>Image</th>
				<th>Name</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Row Total</th>
				<th>Action</th>
			</tr>
			<?php foreach ($items->getData() as $item) : ?>
			<tr>
				<td></td>
				<td><?php echo $item->name; ?></td>
				<td width="10%"><input type="number" name="item[quantity]" class="form-control"></td>
				<td><?php echo $item->price; ?></td>
				<td><?php echo 'total'; ?></td>
				<td><input type="checkbox" name="add[]"></td>
			</tr>
			<?php endforeach; ?>
			<tr>
				<td colspan="4"></td>
				<td colspan="4">total</td>
			</tr>
			<?php endif; ?>
		</table>
	</div>	
</form>
<script type="text/javascript">
	
$("#cancelItemTable").click(function() {
	$("#itemTable").hide();
});
</script>