<?php $items = $this->getItems(); ?>
<?php $quoteItems = $this->getQuoteItems(); ?>
<div id="itemTable">
<form action="<?php echo $this->getUrl('itemsSave'); ?>" method="post">
	<div class="row" style="width: 80%;margin: 10px;">
		<div class="col-10" align="right"><a class="btn btn-danger" id="cancelItemTable">Cancel</a></div>
		<div class="col-2" align="right"><button class="btn btn-primary">Add selected item</button></div>
	</div>
	<div style="width: 80%" class="mt-3">
		<table class="table table-bordered text-center"  border="2px">
			<?php if(!$items): ?>
			<tr>
				<th colspan="2">There is no record</th>
			</tr>	
			<?php else: ?>
			<tr class="table-secondary">
				<th>Image</th>
				<th>Name</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Action</th>
			</tr>
			<?php foreach ($items->getData() as $item) : ?>
			<tr>
				<td></td>
				<td><?php echo $item->name; ?></td>
				<td width="10%"><input type="number" name="item[<?php echo $item->product_id; ?>]" class="form-control"></td>
				<td><?php echo $item->price; ?></td>
				<td><input type="checkbox" name="add[<?php echo $item->product_id; ?>]"></td>
			</tr>
			<?php endforeach; ?>
			<?php endif; ?>
		</table>
	</div>	
</form>
</div>
<div id="quoteItemTable">
<form action="<?php echo $this->getUrl('quoteItemsUpdate'); ?>" method="post">
	<div class="row mt-3" style="width: 80%;">
		<div class="col-10" align="right"><input type="submit" value="Update" class="btn btn-primary"></div>
		<div class="col-2" align="left"><input type="button" class="btn btn-primary" value="New item" id="addNewItems"></div>
	</div>
	<div style="width: 80%" class="mt-3">
		<table class="table table-bordered text-center"  border="2px">
			<?php if(!$quoteItems): ?>
			<tr>
				<th colspan="2">There is no record</th>
			</tr>	
			<?php else: ?>
			<tr class="table-secondary">
				<th>Image</th>
				<th>Name</th>
				<th>Quantity</th>
				<th>Discount</th>
				<th>Price</th>
				<th>Row Total</th>
				<th>Action</th>
			</tr>
			<?php foreach ($quoteItems->getData() as $quoteItem) : ?>
			<tr>
				<td></td>
				<td><?php echo $quoteItem->name; ?></td>
				<td width="10%"><input type="number" name="quoteItem[<?php echo $quoteItem->item_id; ?>][quantity]" class="form-control" value="<?php echo $quoteItem->quantity; ?>"></td>
				<td width="10%"><input type="number" name="quoteItem[<?php echo $quoteItem->item_id; ?>][discount]" class="form-control" value="<?php echo $quoteItem->discount; ?>"></td>
				<td><?php echo $quoteItem->price; ?></td>
				<td><?php $discountAmount = ($quoteItem->discount * $quoteItem->price)/100; 
						echo ($quoteItem->price - $discountAmount) * $quoteItem->quantity;?></td>
				<td><a href="<?php echo $this->getUrl('deleteQuoteItem', null, ['item_id' => $quoteItem->getId()], true); ?>"><img src="Resources/images/delete.png" height="25px"></a></td>
			</tr>
			<?php endforeach; ?>
			<tr>
				<td colspan="4"></td>
				<th colspan="4"><?php echo round($this->getTotal()->total,2); ?></th>
			</tr>
			<?php endif; ?>
		</table>
	</div>	
</form>
</div>
<script type="text/javascript">
	
$("#cancelItemTable").click(function() {
	$("#itemTable").hide();
});

$("#addNewItems").click(function() {
	$("#itemTable").show();
});

$(document).ready(function () {
	$("#itemTable").hide();
})
</script>