<div>
	<table class="mx-4 mt-3 table" style="width: 20%;border-radius: 10pz;">
		<tr>
			<th>SUB TOTAL:</th>
			<td>1500</td>
		</tr>
		<tr>
			<th>SHIPPING:</th>
			<td>100</td>
		</tr>
		<tr>
			<th>TAX:</th>
			<td>150</td>
		</tr>
		<tr>
			<th>DISCOUNT:</th>
			<td>50</td>
		</tr>
		<tr>
			<th>GRAND TOTAL:</th>
			<td>1700</td>
		</tr>
		<tr>
			<th></th>
			<td><button class="btn btn-primary">Place order</button></td>
		</tr>
	</table>
</div>