<div>
	<table class="mx-4 mt-3 table" style="width: 20%;border-radius: 10pz;">
		<tr>
			<th>SUB TOTAL:</th>
			<td><?php echo $subTotal = (int)$this->getTotal(); ?></td>
		</tr>
		<tr>
			<th>SHIPPING:</th>
			<td><?php echo $shippingAmount = (int)$this->getShippingAmount(); ?></td>
		</tr>
		<tr>
			<th>DISCOUNT:</th>
			<td><?php $discountAmount = (!$this->getDiscountAmount()) ? 0 : $this->getDiscountAmount(); ?>
				<?php echo $discount = round($discountAmount, 2); ?>
			</td>
		</tr>
		<tr>
			<th>GRAND TOTAL:</th>
			<td><?php echo $grandTotal = ($subTotal + $shippingAmount) - $discount; $this->setOrderTotal($grandTotal); ?></td>
		</tr>
		<tr>
			<th></th>
			<td><button class="btn btn-primary">Place order</button></td>
		</tr>
	</table>
</div>