<?php 
$customer = $this->getCustomer();
// $customerAddress = $this->getCustomerAddress();
$shippingAddress = $this->getShippingAddress();
$billingAddress = $this->getBillingAddress();
$mode = ($customer->customer_id) ? 'Edit' : 'Add';
?>
<form action="<?php echo $this->getUrl('save'); ?>" method="POST">
<div align="center" class="w-100 container">
	<div class="w-50 align-items-center d-flex row">
		<div align="left" class="col-8">
			<h2><?php echo $mode." customer"; ?></h2>
		</div>
		<div align="right" class="col-2">
			<a href="<?php echo $this->getUrl('grid',null,[],true); ?>" class="btn btn-danger">Cancel</a>
		</div>
		<div align="right" class="col-2">
			<button class="btn btn-primary" name="submit">Save</button>
		</div>
	</div>
	<div class="w-50 mt-2">
		<table class="table table-striped table-hover">
			<tr>
				<th colspan="2"> 
					Customer Information						
				</td>
			</tr>
			<tr>
				<td>
					First Name
				</td>
				<td>
					<input type="text" name="customer[first_name]" value="<?php echo $customer->first_name; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>
					Last Name
				</td>
				<td>
					<input type="text" name="customer[last_name]" value="<?php echo $customer->last_name; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>Email</td>
				<td>
					<input type="email" name="customer[email]" value="<?php echo $customer->email; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>Gender</td>
				<td>
					<ul class="list-group">
					 	<li class="list-group-item">
						    <input class="form-check-input me-1" type="radio" name="customer[gender]" value="1" id="firstRadio" 
						    <?php 
						    if ($customer->gender == 1) {
								echo "checked"; 
							}
							?>>
						    <label class="form-check-label" for="firstRadio">Male</label>
					  	</li>
					  	<li class="list-group-item">
						    <input class="form-check-input me-1" type="radio" name="customer[gender]" value="2" id="secondRadio"
						    <?php 
							if ($customer->gender == 2) {
								echo "checked"; 
							}
							?>>
						    <label class="form-check-label" for="secondRadio">Female</label>
					  	</li>
					</ul>
				</td>
			</tr>
			<tr>
				<td>
					Mobile
				</td>
				<td>
					<input type="tel" value="<?php echo $customer->mobile; ?>" name="customer[mobile]" class="form-control">
				</td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="customer[status]" class="form-control">
						<?php foreach ($customer->getStatusOptions() as $key => $value): 
							$selected = ($key == $customer->getStatus()) ? 'selected' : '';
						?>
						<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
		</table>
	</div>

<div style="width: 50%">
	<div style="width:100%;margin-top:50px" align="left">
		<h2><?php echo $mode." Billing address"; ?></h2>
	</div>
	<div style="width:100%;">
		<table class="table table-striped table-hover">
			<tr>
				<th colspan="2">
					Billing address information
				</th>
			</tr>
			<tr>
				<td>
					Address
				</td>
				<td>
					<input type="text" name="billingAddress[address]" value="<?php echo $billingAddress->address; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>
					City
				</td>
				<td>
					<input type="text" name="billingAddress[city]" value="<?php echo $billingAddress->city; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>
					State
				</td>
				<td>
					<input type="text" name="billingAddress[state]" value="<?php echo $billingAddress->state; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>
					Country
				</td>
				<td>
					<input type="text" name="billingAddress[country]" value="<?php echo $billingAddress->country; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>
					zip code
				</td>
				<td>
					<input type="number" name="billingAddress[zip_code]" value="<?php echo $billingAddress->zip_code; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<div class="form-check">
						<input type="checkbox" name="checkbox" id="sameAddress">
						<label for="sameAddress">same for shipping address</label>
					</div>
				</td>
			</tr>
		</table>
	</div>
</div>

<div style="width: 50%" id="shippingAddressTable">
	<div style="width:100%;margin-top:50px" align="left">
		<h2><?php echo $mode." Shipping address"; ?></h2>
	</div>
	<div style="width:100%;">
		<table class="table table-striped table-hover">
			<tr>
				<th colspan="2">
					Shipping address information
				</th>
			</tr>
			<tr>
				<td>
					Address
				</td>
				<td>
					<input type="text" name="shippingAddress[address]" value="<?php echo $shippingAddress->address; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>
					City
				</td>
				<td>
					<input type="text" name="shippingAddress[city]" value="<?php echo $shippingAddress->city; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>
					State
				</td>
				<td>
					<input type="text" name="shippingAddress[state]" value="<?php echo $shippingAddress->state; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>
					Country
				</td>
				<td>
					<input type="text" name="shippingAddress[country]" value="<?php echo $shippingAddress->country; ?>" class="form-control">
				</td>
			</tr>
			<tr>
				<td>
					zip code
				</td>
				<td>
					<input type="number" name="shippingAddress[zip_code]" value="<?php echo $shippingAddress->zip_code; ?>" class="form-control">
				</td>
			</tr>
		</table>
	</div>
</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function () {
	$('#sameAddress').change(function () {
		if (this.checked) {
			$('#shippingAddressTable').hide();
		} else {
			$('#shippingAddressTable').show();
		}

	});	
});

</script>
