<?php 
$customers = $this->getCustomers();
?>
<div align="center" class="w-100 container">
	<div class="w-90 d-flex align-items-center row">
		<div align="left" class="col-6">
			<h2>Manage Customers</h2>
		</div>
		<div align="right" class="col-6">
			<a href="<?php echo $this->getUrl('add'); ?>">
				<button class="btn btn-primary">Add customer</button>
			</a>
		</div>
	</div>
	<div align="center" class="w-90 mt-2">
		<table class="table table-striped table-hover">
			<?php if ($customers){ ?>
			<tr class="table-dark">
				<th>Customer ID</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Email</th>
				<th>Gender</th>
				<th>Mobile</th>
				<th>Status</th>
				<th>Created At</th>
				<th>Updated At</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<?php foreach($customers->getData() as $customer): ?>
			<tr>
				<td><?php echo $customer->customer_id; ?></td>
				<td><?php echo $customer->first_name; ?></td>
				<td><?php echo $customer->last_name; ?></td>
				<td><?php echo $customer->email; ?></td>
				<td>
					<?php 
					if ($customer->gender == 1) {
						echo "Male";
					}
					elseif ($customer->gender == 2){
						echo "Female";
					}
					?>
				</td>
				<td><?php echo $customer->mobile; ?></td>
				<td>
					<?php 
					$status = $customer->getStatusOptions();
					foreach ($status as $key => $value) {
						if ($customer->status == $key) {
							echo $value;
						}
					}
					?>
					</td>
				<td>
					<?php
					if ($customer->created_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($customer->created_at));
					 }
					?>
				</td>
				<td>
					<?php 
					if ($customer->updated_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($customer->updated_at)); 
					 }
					?>
				</td>
				<td><a href="<?php echo $this->getUrl('edit', null, ['id' => $customer->customer_id]); ?>"><img style="height: 25px;" src="Resources/images/edit.png"></a></td>
				<td><a href="<?php echo $this->getUrl('delete', null, ['id' => $customer->customer_id]); ?>"><img style="height: 25px;" src="Resources/images/delete.png"></a></td>
			</tr>
			<?php endforeach; } 
			else{ ?>
			<tr>
				<td colspan="11">
					<h3>There is no record</h3>
				</td>
			</tr>
			<?php } ?>
		</table>
	</div>
</div>
