<?php 
$payment = $this->getPayment();
$attributes = $this->getAttributes();
$mode = ($payment->payment_method_id) ? 'Edit' : 'Add';
?>
<div align="center" class="w-100 container">
	<form action="<?php echo $this->getUrl('save'); ?>" method="POST">
	<div class="w-50 align-items-center d-flex row">
		<div align="left" class="col-8">
			<h2><?php echo $mode." payment method" ?></h2>
		</div>
		<div align="right" class="col-2">
			<a href="<?php echo $this->getUrl('grid',null,[],true); ?>" class="btn btn-danger">Cancel</a>
		</div>
		<div align="right" class="col-2">
			<button class="btn btn-primary" name="submit">Save</button>
		</div>
	</div>
	<div class="w-50 mt-2">
		<table class="table table-striped table-hover">
			<tr>
				<th colspan="2">Payment method information</th>
			</tr>
			<tr>
				<td>Name</td>
				<td><input type="text" name="payment[name]" value="<?php echo $payment->name; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="payment[status]" class="form-control">
						<?php foreach ($payment->getStatusOptions() as $key => $value): 
							$selected = ($key == $payment->getStatus()) ? 'selected' : '';
						?>
						<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<?php if($attributes): ?>
			<?php foreach ($attributes->getData() as $attribute) : ?>
				<tr>
					<td><?php echo $attribute->name; ?></td>
					<td>
						<?php $inputType = $this->getLayout()->createBlock('Eav_Attribute_InputType')->setAttribute($attribute)->setRow($payment)->render(); ?>
					</td>
				</tr>
			<?php endforeach; ?>
			<?php endif; ?>
		</table>
	</div>
	</form>
</div>
