<?php
$payments = $this->getPayments();
?>
<div align="center" class="w-100 container">
	<div class="w-90 d-flex align-items-center row">
		<div align="left" class="col-6">
			<h2>Manage Payment methods</h2>
		</div>
		<div align="right" class="col-6">
			<a href="<?php echo $this->getUrl('add'); ?>"><button class="btn btn-primary">Add Payment method</button></a>
		</div>
	</div>
	<div class="w-90 mt-2">
		<table class="table table-striped table-hover">
			<?php if($payments){ ?>
			<tr class="table-dark">
				<th>Payment Method ID</th>
				<th>name</th>
				<th>Status</th>
				<th>Created At</th>
				<th>Updated At</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<?php foreach($payments->getData() as $payment): ?>
			<tr>
				<td><?php echo $payment->payment_method_id; ?></td>
				<td><?php echo $payment->name; ?></td>
				<td><?php echo $payment->getStatusText(); ?></td>
				<td>
					<?php 
					if ($payment->created_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($payment->created_at)); 
					 }
					?>
				</td>
				<td>
					<?php 
					if ($payment->updated_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($payment->updated_at)); 
					 }
					?>
				</td>
				<td><a href="<?php echo $this->getUrl('edit', null, ['id' => $payment->payment_method_id]); ?>"><img style="height: 25px;" src="Resources/images/edit.png"></a></td>
				<td><a href="<?php echo $this->getUrl('delete', null, ['id' => $payment->payment_method_id]); ?>"><img style="height: 25px;" src="Resources/images/delete.png"></a></td>
			</tr>
			<?php endforeach; }
			else{ ?>
			<tr>
				<td align="center" colspan="7">
					<h3>There is no record</h3>
				</td>
			</tr>
			<?php } ?>
		</table>
	</div>
</div>
	