<?php
$category = $this->getCategory();
$categories = $category->getParentCategories();
$pathCategories = $this->getPathCategories();
$mode = ($category->category_id) ? 'Edit' : 'Add';
?>
<div align="center" class="w-100 container">
	<form action="<?php echo $this->getUrl('save'); ?>" method="POST">
	<div class="w-50 align-items-center d-flex row">
		<div align="left" class="col-8">  
			<h2><?php echo $mode." category"; ?></h2>
		</div>
		<div align="right" class="col-2">
			<a href="<?php echo $this->getUrl('grid',null,[],true); ?>" class="btn btn-danger">Cancel</a>
		</div>
		<div align="right" class="col-2">
			<button class="btn btn-primary" name="submit">Save</button>
		</div>
	</div>
	<div class="w-50 mt-2">
	<table class="table table-striped table-hover">
		<tr>
			<th colspan="2">
				Category information
			</th>
		</tr>
		<tr>
			<td>
				Name
			</td>
			<td>
				<input type="text" name="category[name]" class="form-control" value="<?php echo $category->name; ?>">
			</td>
		</tr>
		<tr>
			<td>
				Parent category
			</td>
			<td>
				<select name="category[parent_id]" class="form-select">
					<option value="1">Root</option>
					<?php foreach ($categories as $key => $value): 
						if (array_key_exists($key, $pathCategories)): ?>
						<option value="<?php echo $key; ?>"
							<?php 
							if ($mode == 'Edit' && $key == $category->load($category->category_id)->parent_id) {
								echo "selected";
							}
							?>>
							<?php echo $pathCategories[$key]; ?></option>
					<?php endif; endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td>
				Status
			</td>
			<td>
				<select name="category[status]" class="form-select">
						<?php foreach ($category->getStatusOptions() as $key => $value): 
							$selected = ($key == $category->getStatus()) ? 'selected' : '';
						?>
						<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
			</td>
		</tr>
		<tr>
			<td>
				Description
			</td>
			<td>
				<textarea class="form-control" name="category[description]" style="height:50px"><?php echo $category->description; ?></textarea>
			</td>
		</tr>
	</table>
	</div>
	</form>
</div> 