<?php 
$this->fetchData();
$categories = $this->getCategories();
$pathCategories = $this->getPathCategories();	
?>
<div align="center" class="container">
	<div class="w-100 d-flex align-items-center row">
		<div align="left" class="col-6">
			<h2>Manage Categories</h2>
		</div>
		<div align="right" class="col-6">
			<a href="<?php echo $this->getUrl('add'); ?>"><button class="btn btn-primary">Add category</button></a>
		</div>
	</div>
	<div class="w-100 mt-2">
		<table class="table table-striped table-hover text-center">
			<?php if ($categories) { ?>
			<tr class="table-dark">
				<th>Category ID</th>
				<th>Name</th>
				<th>Status</th>
				<th>Description</th>
				<th>Created At</th>
				<th>Updated At</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<?php 
			foreach($categories->getData() as $category):
			?>
			<tr>
				<td><?php echo $category->category_id; ?></td>
				<td style="text-align: left;">
					<?php
					if (array_key_exists($category->category_id, $pathCategories)) {
						echo $pathCategories[$category->category_id];
					}
					?>
				</td>
				<td><?php echo $category->getStatusText(); ?></td>
				<td><?php echo $category->description; ?></td>
				<td>
					<?php 
					if ($category->created_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($category->created_at)); 
					 }
					?>
				</td>
				<td>
					<?php 
					if ($category->updated_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($category->updated_at)); 
					 }
					?>
				</td>
				<td><a href="<?php echo $this->getUrl('edit', null, ['id' => $category->category_id]); ?>">Edit</a></td>
				<td><a href="<?php echo $this->getUrl('delete', null, ['id' => $category->category_id]); ?>">Delete</a></td>
			</tr>
		<?php endforeach; } 
		else{
			?>
			<tr>
				<td colspan="8">
					<h3>There is no record</h3>
				</td>
			</tr>
			<?php } ?>
		</table>
	</div>
</div>
	