<?php 
$salesman = $this->getSalesman();
$salesmanAddress = $this->getSalesmanAddress();
$mode = ($salesman->salesman_id) ? 'Edit' : 'Add';
?>
<div align="center" class="w-100 container">
	<form action="<?php echo $this->getUrl('save'); ?>" method="POST" id="salesman-form">
	<div class="w-50 align-items-center d-flex row">
		<div align="left" class="col-8">
			<h2><?php echo $mode." salesman"; ?></h2>
		</div>
		<div align="right" class="col-2">
			<a onclick="ajax.setUrl('<?php echo $this->getUrl('grid',null,[],true); ?>').call()" class="btn btn-danger">Cancel</a>
		</div>
		<div align="right" class="col-2">
			<input type="button" class="btn btn-primary" onclick="ajax.setForm('salesman-form').call()" value="Save">
		</div>
	</div>
	<div class="w-50 mt-2">
		<table class="table table-striped table-hover">
			<tr>
				<th colspan="2">Salesman Information</th>
			</tr>
			
			<tr>
				<td>First Name</td>
				<td><input type="text" name="salesman[first_name]" value="<?php echo $salesman->first_name; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>Last Name</td>
				<td><input type="text" name="salesman[last_name]" value="<?php echo $salesman->last_name; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>Email</td>
				<td><input type="email" name="salesman[email]" value="<?php echo $salesman->email; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>Gender</td>
				<td>
					<ul class="list-group">
					 	<li class="list-group-item">
						    <input class="form-check-input me-1" type="radio" name="salesman[gender]" value="1" id="firstRadio" 
						    <?php 
						    if ($salesman->gender == 1) {
								echo "checked"; 
							}
							?>>
						    <label class="form-check-label" for="firstRadio">Male</label>
					  	</li>
					  	<li class="list-group-item">
						    <input class="form-check-input me-1" type="radio" name="salesman[gender]" value="2" id="secondRadio"
						    <?php 
							if ($salesman->gender == 2) {
								echo "checked"; 
							}
							?>>
						    <label class="form-check-label" for="secondRadio">Female</label>
					  	</li>
					</ul>
				</td>
			</tr>
			<tr>
				<td>Mobile</td>
				<td><input type="tel" name="salesman[mobile]" class="form-control" value="<?php echo $salesman->mobile; ?>"></td>
			</tr>
			<tr>
				<td>status</td>
				<td>
					<select name="salesman[status]" class="form-control">
						<?php foreach ($salesman->getStatusOptions() as $key => $value): 
							$selected = ($key == $salesman->getStatus()) ? 'selected' : '';
						?>
						<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
					</select>
				</td>
			</tr>
			<tr>
				<td>Company</td>
				<td><input type="text" name="salesman[company]" class="form-control" value="<?php echo $salesman->company; ?>"></td>
			</tr>
		</table>
	</div>
	<div style="width:50%;margin-top: 50px" align="left">
		<h2><?php echo $mode." salesman address"; ?></h2>
	</div>
	<div style="width:50%">
		<table class="table table-striped table-hover">
			<tr>
				<th colspan="2">Salesman's address information</th>
			</tr>
			<tr>
				<td>Address</td>
				<td><input type="text" name="salesmanAddress[address]" value="<?php echo $salesmanAddress->address; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>City</td>
				<td><input type="text" name="salesmanAddress[city]" value="<?php echo $salesmanAddress->city; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>State</td>
				<td><input type="text" name="salesmanAddress[state]" value="<?php echo $salesmanAddress->state; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>Country</td>
				<td><input type="text" name="salesmanAddress[country]" value="<?php echo $salesmanAddress->country; ?>" class="form-control"></td>
			</tr>
			<tr>
				<td>zip code</td>
				<td><input type="text" name="salesmanAddress[zip_code]" value="<?php echo $salesmanAddress->zip_code; ?>" class="form-control"></td>
			</tr>
		</table>
	</div>
	</form>
</div>
