<?php
$salesmen = $this->getSalesmen();
?>
<div align="center" class="w-100 container">
	<div class="w-90 d-flex align-items-center">
		<div align="left" class="col-6">
			<h2>Manage Salesmen</h2>
		</div>
		<div align="right" class="col-6">
			<a href="<?php echo $this->getUrl('add'); ?>"><button class="btn btn-primary">Add Salesman</button></a>
		</div>
	</div>
	<div class="w-90 mt-2">
		<table class="table table-striped table-hover">
			<?php if($salesmen){ ?>
			<tr class="table-dark">
				<th>Salesman ID</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Email</th>
				<th>Gender</th>
				<th>Mobile</th>
				<th>Status</th>
				<th>Company</th>
				<th>Created At</th>
				<th>Updated At</th>
				<th>Price</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<?php foreach($salesmen->getData() as $salesman): ?>
			<tr>
				<td><?php echo $salesman->salesman_id; ?></td>
				<td><?php echo $salesman->first_name; ?></td>
				<td><?php echo $salesman->last_name; ?></td>
				<td><?php echo $salesman->email; ?></td>
				<td>
					<?php 
					if ($salesman->gender == 1) {
						echo "Male";
					}
					elseif ($salesman->gender == 2) {
						echo "Female";
					}
					?>
				</td>
				<td><?php echo $salesman->mobile; ?></td>
				<td><?php echo $salesman->getStatusText(); ?></td>
				<td><?php echo $salesman->company; ?></td>
				<td>
					<?php 
					if ($salesman->created_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($salesman->created_at)); 
					 }
					?>
				</td>
				<td>
					<?php 
					if ($salesman->updated_at == NULL) {
					 	echo "";
					 } 
					 else{
					 	echo date('Y/m/d h:i:s a',strtotime($salesman->updated_at)); 
					 }
					?>
				</td>
				<td><a href="<?php echo $this->getUrl('grid', 'salesman_price', ['id' => $salesman->salesman_id]); ?>"><img style="height: 30px;" src="Resources/images/prices.png"></a></td>
				<td><a href="<?php echo $this->getUrl('edit', null, ['id' => $salesman->salesman_id]); ?>"><img style="height: 25px;" src="Resources/images/edit.png"></a></td>
				<td><a href="<?php echo $this->getUrl('delete', null, ['id' => $salesman->salesman_id]); ?>"><img style="height: 25px;" src="Resources/images/delete.png"></a></td>
			</tr>
			<?php endforeach; } 
			else{ ?>
			<tr>
				<td colspan="13">
					<h3>There is no record</h3>
				</td>
			</tr>
			<?php } ?>
		</table>
	</div>
</div>
