<?php
$rows = $this->getCollection();
$pager = $this->getPager();
// echo '<pre>';
// print_r($pager);
?>
<div style="width: 90%">
	<div class="w-90 d-flex align-items-center row">
		<div align="left" class="col-6">
			<h2><?php echo $this->getTitle(); ?></h2>
		</div>
		<div align="right" class="col-6">
			<?php foreach ($this->getButtons() as $key => $button) : ?>
				<a onclick="ajax.setUrl('<?php echo $button['url']; ?>').call()" class="btn btn-primary"><?php echo $button['title']; ?></a>
			<?php endforeach; ?>
			<!-- <a href="<?php echo $this->getUrl('export', 'product', null, true); ?>" class="btn btn-primary">Export</a>
			<a href="<?php echo $this->getUrl('import', 'product', null, true); ?>" class="btn btn-primary">Import</a> -->
		</div>
	</div>
	<div class="mt-2 w-90">
		<table class="w-90 table table-striped table-hover" border="1">
			<?php if(!$rows): ?>
			<tr>
				<td align="center" colspan="7"><h3>There is no record</h3></td>
			</tr>
			<?php else: ?>
			<tr class="table-dark">
				<?php foreach ($this->getColumns() as $key => $column) : ?>
					<th><?php echo $column['title']; ?></th>
				<?php endforeach; ?>

				<?php foreach ($this->getActions() as $key => $action) : ?>
					<th><?php echo $action['title']; ?></th>
				<?php endforeach; ?>
			</tr>
			<?php foreach($rows->getData() as $row): ?>
			<tr>
				<?php foreach ($this->getColumns() as $key => $column) : ?>
					<td><?php echo $this->getColumnValue($row, $key); ?></td>
				<?php endforeach; ?>

				<?php foreach ($this->getActions() as $key => $action) : ?>
				<td><a onclick="ajax.setUrl('<?php $method = $action['method']; echo $this->$method($row, $key); ?>').call()"><img height="30px" src="Resources/images/<?php echo (array_key_exists('name', $action)) ? $action['name'] : $key; ?>.png" alt="<?php echo $key; ?>"></a></td>
				<?php endforeach; ?>
			</tr>
			<?php endforeach; ?>
			<?php endif; ?>
		</table>
	</div>
</div>
<div class="row" style="width: 90%; align-items: center;">
	<div class="col-2" align="left"><?php echo "<b>Total Records : </b>".$pager->getTotalRecords(); ?></div>
	<div class="col-3 d-flex align-items-center" align="left">
		<div class="col-5" align="left"><b>Record count :</b></div>
		<div class="col-3" align="left">
			<form action="<?php echo $this->getUrl('grid'); ?>" method="post" id="change-record-count">
				<select class="form-select col-2" name='rpp' id="show-record-count">
					<?php $numberofRecords = ['10'=>10,'20'=>20,'50'=>50,'100'=>100,'200'=>200,'500'=>500]; ?>
					<?php foreach($numberofRecords as $key => $value): ?>
						<option value="<?php echo $key; ?>" 
							<?php echo ($pager->getRecordPerPage() == $key) ? 'selected' : ''; ?>>
							<?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
				<input type="hidden" name="p" id="page-no" value="<?php echo $pager->getCurrentPage(); ?>">
			</form>
		</div>
	</div>
	<div class="col-2" align="right">
		<nav aria-label="Page navigation">
			<ul class="pagination justify-content-center mt-3">
			    <li class="page-item <?php echo ($pager->getStart() == 0) ? 'disabled' : '';?>"><a id="page-link-start" class="page-link">start</a></li>

			    <li class="page-item <?php echo ($pager->getPrevious() == 0) ? 'disabled' : '';?>"><a id="page-link-pre" class="page-link">
			    	<span aria-hidden="true">&laquo;</span></a></li>

			    <li class="page-item"><a id="page-link-current" class="page-link"><?php echo $pager->getCurrentPage(); ?></a></li>

			    <li class="page-item <?php echo ($pager->getNext() == 0) ? 'disabled' : '';?>"><a id="page-link-next" class="page-link"><span aria-hidden="true">&raquo;</span></a></li>

			    <li class="page-item <?php echo ($pager->getEnd() == 0) ? 'disabled' : '';?>"><a id="page-link-end" class="page-link">end</a></li>
			</ul>
		</nav>
	</div>
	<div class="col-3">&nbsp;</div>
	<div class="col-2">
		<?php echo "showing <span class='fw-bold'>Page ".$pager->getCurrentPage()."</span> of <span class='fst-italic fw-bold'>Total ".$pager->getNumberOfPages()."</span>" ?>
	</div>
</div>
<script type="text/javascript">
	$('#show-record-count').change(function () {
		ajax.setForm('change-record-count').call();
	});	
	$('#page-link-start').click(function () {
		$('#page-no').attr('value', <?php echo $pager->getStart(); ?>) ;
		ajax.setForm('change-record-count').call();
	});
	$('#page-link-pre').click(function () {
		$('#page-no').attr('value', <?php echo $pager->getPrevious(); ?>) ;
		ajax.setForm('change-record-count').call();
	});
	$('#page-link-current').click(function () {
		$('#page-no').attr('value', <?php echo $pager->getCurrentPage(); ?>) ;
		ajax.setForm('change-record-count').call();
	});
	$('#page-link-next').click(function () {
		$('#page-no').attr('value', <?php echo $pager->getNext(); ?>) ;
		ajax.setForm('change-record-count').call();
	});
	$('#page-link-end').click(function () {
		$('#page-no').attr('value', <?php echo $pager->getEnd(); ?>) ;
		ajax.setForm('change-record-count').call();
	});
</script>
